import { Reveal } from "@/components/ui/reveal";
import { Section } from "@/components/ui/section";
import { Microscope, PenTool, Zap, X, Check } from "lucide-react";

export function HowItWorks() {
  const oldWay = [
    "Bought lists from ZoomInfo and Apollo",
    "Template emails with merge tags",
    "Shared sending infrastructure",
    "Flagged as promotional, lands in spam",
    "Same prospects your competitors are emailing",
  ];

  const autoUpWay = [
    "AI-built databases exclusive to each client",
    "Every sequence written by strategists who've sent millions of emails",
    "Proprietary infrastructure, warmed and scaled in real time",
    "Hits primary inbox consistently",
    "Fresh contacts your competitors can't access",
  ];

  return (
    <Section id="how-it-works" className="bg-white">
      <div className="text-center max-w-3xl mx-auto mb-10">
        <Reveal>
          <div className="text-teal font-bold uppercase tracking-widest text-sm mb-4">The System</div>
          <h2 className="text-3xl md:text-5xl font-bold mb-6 text-[#1e293b]">
            10,000+ Positive Replies.<br /><em>Every Month.</em>
          </h2>
          <p className="text-[20px] text-[#64748b] leading-relaxed">
            Not opens. Not clicks. Positive replies from verified decision-makers — generated by an outbound engine built on proprietary data, reply-optimized copy, and infrastructure that hits primary at scale.
          </p>
        </Reveal>
      </div>

      <Reveal delay={0.15}>
        <div className="grid md:grid-cols-2 gap-8 max-w-5xl mx-auto mb-16">
          <div
            className="bg-white rounded-xl border border-[#eef1f5] p-8 md:p-10"
            data-testid="card-old-way"
          >
            <div className="text-[13px] font-bold uppercase tracking-[2px] text-[#8a9bb0] mb-8">The Old Way</div>
            <div className="space-y-5">
              {oldWay.map((item, i) => (
                <div key={i} className="flex items-start gap-4">
                  <div className="flex-shrink-0 w-6 h-6 rounded-full bg-red-500/10 flex items-center justify-center mt-0.5">
                    <X className="w-3.5 h-3.5 text-red-500" />
                  </div>
                  <span className="text-[17px] text-[#64748b] leading-relaxed">{item}</span>
                </div>
              ))}
            </div>
          </div>

          <div
            className="bg-[#0c1b2e] rounded-xl border border-[#00C9DB]/20 p-8 md:p-10"
            data-testid="card-autoup-system"
          >
            <div className="text-[13px] font-bold uppercase tracking-[2px] text-[#00C9DB] mb-8">The AutoUp System</div>
            <div className="space-y-5">
              {autoUpWay.map((item, i) => (
                <div key={i} className="flex items-start gap-4">
                  <div className="flex-shrink-0 w-6 h-6 rounded-full bg-[#00C9DB]/10 flex items-center justify-center mt-0.5">
                    <Check className="w-3.5 h-3.5 text-[#00C9DB]" />
                  </div>
                  <span className="text-[17px] text-white/90 leading-relaxed">{item}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </Reveal>

      <div className="grid md:grid-cols-3 gap-8">
        {[
          {
            icon: <Microscope className="w-8 h-8 text-teal" />,
            title: "Your Data, Not a List",
            desc: "We don't buy from ZoomInfo or Apollo. We build custom databases with AI scrapers that find verified contacts your competitors can't access."
          },
          {
            icon: <PenTool className="w-8 h-8 text-teal" />,
            title: "Copy That Sounds Human",
            desc: "No templates, no merge tags. Every sequence is written by real strategists who've sent millions of emails and know what converts."
          },
          {
            icon: <Zap className="w-8 h-8 text-teal" />,
            title: "Proprietary Infrastructure",
            desc: "Warmed inboxes, scaled laterally, real-time monitoring — built on a sending method no one else has. Your emails hit primary while your competitors land in spam."
          }
        ].map((item, i) => (
          <Reveal key={i} delay={i * 0.1} className="bg-[#f7f8fa] border border-[#eef1f5] p-10 rounded-2xl hover:border-[#d0d5dd] hover:shadow-md hover:-translate-y-0.5 transition-all group">
            <div className="bg-teal/10 w-16 h-16 rounded-xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform duration-300">
              {item.icon}
            </div>
            <h3 className="text-[22px] font-bold mb-4 font-sans text-[#1e293b]">{item.title}</h3>
            <p className="text-[#64748b] leading-[1.8] text-[18px]">{item.desc}</p>
          </Reveal>
        ))}
      </div>
    </Section>
  );
}
