import { Reveal } from "@/components/ui/reveal";
import { Navigation } from "@/components/sections/Navigation";
import { Footer } from "@/components/sections/Footer";
import { BlogCTA } from "@/components/BlogCTA";
import { usePageMeta } from "@/hooks/usePageMeta";

export default function Terms() {
  usePageMeta({
    title: "Terms & Privacy — AutoUp",
    description: "AutoUp Terms of Use, Privacy Policy, and Data Processing Agreement.",
    canonical: "https://autoup.io/terms",
  });

  return (
    <div className="min-h-screen bg-white">
      <Navigation />

      <article className="pt-32 pb-20">
        <div className="container mx-auto px-4 md:px-6 max-w-3xl">
          <Reveal>
            <div className="mb-8">
              <h1 className="font-bold text-gray-900 mb-3 leading-tight font-serif italic" style={{ fontSize: '32px' }} data-testid="text-terms-title">
                Terms & Privacy
              </h1>
              <p className="text-sm text-gray-400 mb-8">Last updated: February 22, 2026</p>
            </div>
          </Reveal>

          <Reveal delay={0.1}>
            <nav className="mb-12 p-6 bg-gray-50 rounded-lg" data-testid="terms-toc">
              <p className="text-sm font-semibold text-gray-900 mb-3">Table of Contents</p>
              <ul className="space-y-2">
                <li>
                  <a href="#terms-of-use" className="text-[15px] text-[#4580F7] hover:underline transition-colors">Terms of Use</a>
                </li>
                <li>
                  <a href="#privacy-policy" className="text-[15px] text-[#4580F7] hover:underline transition-colors">Privacy Policy</a>
                </li>
                <li>
                  <a href="#data-processing-agreement" className="text-[15px] text-[#4580F7] hover:underline transition-colors">Data Processing Agreement</a>
                </li>
              </ul>
            </nav>
          </Reveal>

          <Reveal delay={0.2}>
            <section id="terms-of-use" className="scroll-mt-28">
              <h2 className="text-2xl font-bold text-gray-900 mb-8 font-sans">Terms of Use</h2>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">1. Acceptance of Terms</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">By accessing the website at https://autoup.io/ or engaging AutoUp's services, you agree to be bound by these Terms of Use, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this site or our services. The materials contained in this website are protected by applicable copyright and trademark law.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">2. Description of Services</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">AutoUp provides outbound email campaign services, including but not limited to: custom prospect database building, email sequence creation and optimization, email sending infrastructure provisioning and management, campaign monitoring and performance reporting, and deliverability optimization. These services are provided pursuant to a separate Master Service Agreement or Statement of Work between AutoUp and each client.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">3. Service Terms and Engagement</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">All client engagements begin with a three-month initial commitment period designed to provide sufficient volume and data to demonstrate system effectiveness. Following the initial commitment, services continue on a month-to-month basis. Pricing is determined by volume, targeting complexity, and infrastructure requirements, and is outlined in each client's individual agreement.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">4. Client Responsibilities</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">Clients are responsible for: providing accurate information about their business, products, and services for use in campaign messaging; ensuring that the products and services promoted through AutoUp campaigns comply with all applicable laws; responding to qualified leads and replies generated by campaigns in a timely manner; and complying with all terms outlined in their individual service agreement.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">5. Acceptable Use</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">You agree not to use AutoUp's services to: send emails promoting illegal products, services, or activities; transmit content that is defamatory, obscene, or otherwise objectionable; violate any applicable anti-spam laws, including CAN-SPAM, CASL, GDPR, or any other relevant legislation; harvest or collect email addresses or other contact information through deceptive means; or engage in any activity that could damage, disable, or impair AutoUp's infrastructure or interfere with any other party's use of our services.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">6. Intellectual Property</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">AutoUp retains all rights, title, and interest in its proprietary systems, processes, email sequences, sending infrastructure, data sourcing methodologies, and all related intellectual property. Clients may not reverse-engineer, replicate, or disclose AutoUp's proprietary methods, campaign strategies, or infrastructure configurations to any third party.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">7. Disclaimer of Warranties</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">AutoUp's services and website materials are provided on an "as is" basis. AutoUp makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. AutoUp does not guarantee specific campaign results, reply rates, or conversion outcomes, as these depend on numerous factors beyond AutoUp's control.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">8. Limitation of Liability</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">In no event shall AutoUp or its vendors, subcontractors, or affiliates be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation damages for loss of data, profit, revenue, or business opportunity, arising out of the use or inability to use AutoUp's services or website, even if AutoUp has been notified of the possibility of such damage. AutoUp's total liability shall not exceed the fees paid by the client during the three-month period preceding the claim. Some jurisdictions do not allow limitations on implied warranties or liability for consequential or incidental damages; in such jurisdictions, liability is limited to the greatest extent permitted by law.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">9. Indemnification</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">You agree to indemnify, defend, and hold harmless AutoUp, its officers, directors, employees, and agents from and against any and all claims, liabilities, damages, losses, and expenses arising out of or related to: your use of AutoUp's services; your violation of these Terms; your violation of any rights of another party; or any content you provide for use in campaigns.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">10. Email Compliance</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">AutoUp designs and operates all campaigns in compliance with applicable email marketing laws, including CAN-SPAM (United States), CASL (Canada), GDPR (European Union), and other relevant anti-spam and data protection regulations. All emails include functioning unsubscribe mechanisms, valid sender identification, and accurate header information. AutoUp maintains suppression lists and honors all opt-out requests promptly.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">11. Links and Third-Party Services</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">AutoUp's website and services may contain links to third-party websites or integrate with third-party platforms. AutoUp is not responsible for the content, privacy policies, or practices of any third-party sites or services. Use of any linked website or integrated service is at your own risk.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">12. Modifications</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">AutoUp reserves the right to revise these Terms of Use at any time. Material changes will be communicated to active clients via email at least 30 days prior to taking effect. Continued use of the website or services after changes are posted constitutes acceptance of the revised terms.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">13. Termination</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">AutoUp may suspend or terminate access to its services at any time for violation of these Terms, non-payment, or any conduct that AutoUp reasonably determines to be harmful to its systems, reputation, or other clients. Upon termination, all rights granted to you under these Terms will immediately cease.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">14. Governing Law</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">These terms and conditions are governed by and construed in accordance with the laws of the State of West Virginia, without regard to its conflict of law principles. You irrevocably submit to the exclusive jurisdiction of the courts located in West Virginia for any disputes arising under these Terms.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">15. Severability</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">If any provision of these Terms is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary, and the remaining provisions shall remain in full force and effect.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">16. Contact</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">For questions about these Terms of Use, contact us at <a href="mailto:legal@autoup.io" className="text-[#4580F7] hover:underline">legal@autoup.io</a>.</p>
            </section>
          </Reveal>

          <hr className="border-0 border-t border-[#e0e0e0] my-12" />

          <Reveal>
            <section id="privacy-policy" className="scroll-mt-28">
              <h2 className="text-2xl font-bold text-gray-900 mb-2 font-sans">Privacy Policy</h2>
              <p className="text-sm text-gray-400 mb-8">Effective: February 22, 2026</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">1. Overview</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">Your privacy is important to us. This Privacy Policy explains how AutoUp ("we," "us," or "our") collects, uses, stores, and protects information when you visit our website (https://autoup.io), use our services, or interact with us in any way. This policy covers two categories of individuals: website visitors and clients who use our outbound email services.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">2. Information We Collect</h3>
              <h4 className="text-base font-bold italic text-gray-900 mt-6 mb-2 font-sans">2.1 Website Visitors</h4>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">When you visit our website, we may collect: information you voluntarily provide through contact forms, booking links, or other input fields (such as your name, email address, company name, and phone number); automatically collected technical data including IP address, browser type, device information, and pages visited; and cookies and similar tracking technologies as described in Section 6.</p>

              <h4 className="text-base font-bold italic text-gray-900 mt-6 mb-2 font-sans">2.2 Clients</h4>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">When you engage our services, we additionally collect: business contact information for account setup and communication; billing and payment information processed through secure third-party payment processors; campaign performance data including send volumes, reply rates, and engagement metrics; and information you provide for use in email campaigns, including target audience descriptions and messaging preferences.</p>

              <h4 className="text-base font-bold italic text-gray-900 mt-6 mb-2 font-sans">2.3 Prospect Data</h4>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">In the course of providing our services, we build and manage prospect databases on behalf of our clients. This data may include: business email addresses, names, job titles, company names, company information (industry, size, location), and publicly available professional information. This prospect data is sourced from publicly available business directories, professional networking platforms, company websites, proprietary data providers and AI-assisted research tools, and other lawful sources. We do not knowingly collect personal email addresses, consumer data, or information about individuals under the age of 16.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">3. How We Use Information</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">We use collected information to: provide and improve our outbound email campaign services; build targeted prospect databases exclusive to each client; communicate with clients about campaign performance and account matters; comply with legal obligations, including email marketing regulations; improve our website, systems, and service offerings; and protect against fraud, abuse, and unauthorized access.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">4. Data Sharing</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">We do not sell personal information to third parties under any circumstances. We may share information with: service providers and subprocessors who assist in delivering our services (such as email infrastructure providers, data enrichment tools, and analytics platforms), subject to appropriate data processing agreements; legal authorities when required by law, court order, or governmental regulation; and professional advisors (legal, accounting) as necessary for business operations. All third-party service providers are contractually obligated to protect the confidentiality and security of any data they process on our behalf.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">5. Data Retention</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">We retain client account information for the duration of the business relationship plus three years for legal and compliance purposes. Campaign performance data is retained for the duration of the client relationship plus one year. Prospect databases built for clients are maintained for the duration of the engagement and deleted within 90 days of contract termination unless otherwise agreed. Website visitor data collected through forms is retained for up to two years. Suppression lists (opt-outs) are retained indefinitely to ensure ongoing compliance.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">6. Cookies and Tracking</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">Our website uses cookies and similar technologies to analyze website traffic and usage patterns, improve user experience, and track the effectiveness of our marketing efforts. You may control cookie preferences through your browser settings. Disabling cookies may limit certain website functionality.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">7. Data Security</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">We implement commercially reasonable administrative, technical, and physical security measures to protect information against unauthorized access, disclosure, alteration, or destruction. These measures include encryption of data in transit and at rest, access controls limiting data access to authorized personnel, regular security assessments and monitoring, and secure infrastructure management practices. While we strive to protect all information in our care, no method of electronic transmission or storage is 100% secure, and we cannot guarantee absolute security.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">8. International Data Transfers</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">AutoUp operates primarily from the United States. If you are located outside the United States, please be aware that information may be transferred to, stored, and processed in the United States or other jurisdictions where our service providers operate. By using our services, you consent to the transfer of your information to jurisdictions that may have different data protection laws than your country of residence. Where required, we implement appropriate safeguards for international data transfers, including Standard Contractual Clauses where applicable.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">9. Your Rights</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">Depending on your jurisdiction, you may have the following rights regarding your personal information: right to access, right to rectification, right to erasure, right to restrict processing, right to data portability, right to object, and right to opt-out of sale. To exercise any of these rights, contact us at <a href="mailto:privacy@autoup.io" className="text-[#4580F7] hover:underline">privacy@autoup.io</a>. We will respond to all legitimate requests within 30 days.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">10. California Privacy Rights (CCPA/CPRA)</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">If you are a California resident, you have additional rights under the California Consumer Privacy Act (CCPA) and the California Privacy Rights Act (CPRA), including: the right to know what personal information we collect, use, disclose, and sell; the right to delete personal information we hold about you; the right to correct inaccurate personal information; the right to opt-out of the sale or sharing of personal information (AutoUp does not sell personal information); the right to limit use and disclosure of sensitive personal information; and the right to non-discrimination for exercising your privacy rights. AutoUp does not knowingly collect or sell the personal information of individuals under 16 years of age. To exercise your California privacy rights, contact us at <a href="mailto:privacy@autoup.io" className="text-[#4580F7] hover:underline">privacy@autoup.io</a>.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">11. European Data Subjects (GDPR)</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">If you are located in the European Economic Area (EEA) or the United Kingdom, we process your personal data on the following lawful bases: legitimate interest (for B2B outbound email to business contacts using publicly available professional information); contractual necessity (for data required to fulfill our service agreements); consent (where explicitly provided); and legal obligation (where required by applicable law). You have the right to lodge a complaint with your local data protection authority if you believe your rights have been violated. Our Data Protection contact can be reached at <a href="mailto:privacy@autoup.io" className="text-[#4580F7] hover:underline">privacy@autoup.io</a>.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">12. Prospect Opt-Out</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">If you have received an email sent through AutoUp's infrastructure and wish to opt out of future communications, you may: use the unsubscribe link included in the email; reply to the email requesting removal; or contact us directly at <a href="mailto:privacy@autoup.io" className="text-[#4580F7] hover:underline">privacy@autoup.io</a>. Opt-out requests are processed within 10 business days. Once opted out, your email address is added to our global suppression list to prevent future contact across all client campaigns.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">13. Children's Privacy</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">AutoUp's services are designed for business-to-business communications. We do not knowingly collect personal information from individuals under 16 years of age. If we become aware that we have collected such information, we will take prompt steps to delete it.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">14. Changes to This Policy</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">We may update this Privacy Policy from time to time. Material changes will be posted on our website and, for active clients, communicated via email. Your continued use of our website or services after any changes constitutes acceptance of the updated policy.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">15. Contact Us</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">For any questions, concerns, or requests regarding this Privacy Policy or our data practices:</p>
              <p className="text-gray-600 leading-relaxed mb-1 text-[17px]">Email: <a href="mailto:privacy@autoup.io" className="text-[#4580F7] hover:underline">privacy@autoup.io</a></p>
              <p className="text-gray-600 leading-relaxed mb-1 text-[17px]">Website: <a href="https://autoup.io" className="text-[#4580F7] hover:underline">https://autoup.io</a></p>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">Mailing Address: AutoUp, Charles Town, WV 25414</p>
            </section>
          </Reveal>

          <hr className="border-0 border-t border-[#e0e0e0] my-12" />

          <Reveal>
            <section id="data-processing-agreement" className="scroll-mt-28">
              <h2 className="text-2xl font-bold text-gray-900 mb-8 font-sans">Data Processing Agreement</h2>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">This Data Processing Agreement ("DPA") forms part of the service agreement between AutoUp ("Processor") and the client ("Controller") and governs the processing of personal data by AutoUp on behalf of the client.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">1. Definitions</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]"><strong>Personal Data:</strong> Any information relating to an identified or identifiable natural person, including business contact information processed in the course of providing services.</p>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]"><strong>Processing:</strong> Any operation performed on personal data, including collection, storage, use, transmission, and deletion.</p>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]"><strong>Controller:</strong> The client who determines the purposes and means of processing personal data.</p>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]"><strong>Processor:</strong> AutoUp, which processes personal data on behalf of the Controller.</p>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]"><strong>Subprocessor:</strong> Any third party engaged by AutoUp to assist in the processing of personal data.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">2. Scope and Purpose</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">AutoUp processes personal data solely for the purpose of providing outbound email campaign services as described in the service agreement. The categories of data processed include: business contact information (names, email addresses, job titles, company details), campaign engagement data (opens, clicks, replies), and any additional data fields provided by the Controller for campaign personalization.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">3. Processor Obligations</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">AutoUp shall: process personal data only on documented instructions from the Controller, unless required by law; ensure that persons authorized to process personal data are bound by appropriate confidentiality obligations; implement appropriate technical and organizational security measures; assist the Controller in responding to data subject requests; notify the Controller without undue delay upon becoming aware of a personal data breach; delete or return all personal data upon termination of the service agreement, at the Controller's choice; and make available all information necessary to demonstrate compliance with this DPA and allow for audits.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">4. Subprocessors</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">AutoUp uses subprocessors to assist in providing services, including email sending infrastructure providers, data enrichment services, and analytics platforms. AutoUp maintains a current list of subprocessors, available upon request. AutoUp will notify the Controller of any intended changes to subprocessors, providing the Controller an opportunity to object. All subprocessors are bound by data processing agreements that impose obligations no less protective than those in this DPA.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">5. International Transfers</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">Where personal data is transferred outside the EEA or UK, AutoUp ensures appropriate safeguards are in place, including Standard Contractual Clauses approved by the European Commission or other legally recognized transfer mechanisms.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">6. Data Breach Notification</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">In the event of a personal data breach, AutoUp will notify the Controller without undue delay and in any event within 72 hours of becoming aware of the breach. The notification will include: a description of the nature of the breach, including categories and approximate number of data subjects affected; the name and contact details of the point of contact for further information; a description of the likely consequences of the breach; and a description of measures taken or proposed to address the breach.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">7. Data Subject Requests</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">AutoUp will promptly notify the Controller of any requests received directly from data subjects and will assist the Controller in fulfilling its obligation to respond to such requests. AutoUp will not respond to data subject requests directly unless authorized by the Controller or required by law.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">8. Audit Rights</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">The Controller may audit AutoUp's compliance with this DPA upon reasonable notice (no less than 30 days). Audits shall be conducted during business hours, no more than once per year, and at the Controller's expense. AutoUp may satisfy audit requests by providing relevant certifications, audit reports, or other documentation.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">9. Duration and Termination</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">This DPA remains in effect for the duration of the service agreement between AutoUp and the Controller. Upon termination, AutoUp will delete all personal data processed on behalf of the Controller within 90 days, unless retention is required by law or the Controller requests data return in a standard format.</p>

              <h3 className="text-lg font-bold text-gray-900 mt-8 mb-3 font-sans">10. Liability</h3>
              <p className="text-gray-600 leading-relaxed mb-6 text-[17px]">Each party's liability under this DPA is subject to the limitations of liability set forth in the Terms of Use and the applicable service agreement.</p>
            </section>
          </Reveal>

          <hr className="border-0 border-t border-[#e0e0e0] mt-[80px] mb-[40px]" />

          <div className="mb-12">
            <BlogCTA />
          </div>
        </div>
      </article>

      <Footer />
    </div>
  );
}
